### ISSUE TITLE
How does the request to the server even work?

### ISSUE THREAD

**Issue by chrisgamedev** [supromikali/react-express-session-auth#2]
In the react app, you do a fetch request:
![image](https://user-images.githubusercontent.com/48895916/123599649-2fb41a80-d839-11eb-9fb4-7301af89b5ba.png)

Which results in an outgoing request with a URL of:
![image](https://user-images.githubusercontent.com/48895916/123599750-48bccb80-d839-11eb-9db8-f178f4a98f7e.png)

However, the server is running on port 5000:
![image](https://user-images.githubusercontent.com/48895916/123599820-5bcf9b80-d839-11eb-863d-de59c5a8e3cd.png)

Yet, what confuses me the most is that this works! And when I change the fetch request to use the correct port, it fails (even after fixing the CORS issues).

How does this example work?

**Comment by supromikali** [comment]
Hi @timeBenter , the trick is that create-react-app is using the proxy for all of the /api requests to the url specified in the package.json.

Here is a line of code in question https://github.com/supromikali/react-express-session-auth/blob/master/package.json#L33

And here is a link to the create-react-app docs https://create-react-app.dev/docs/proxying-api-requests-in-development/

**Comment by aathirag** [comment]
Hi I tried this but the res.session.passport is not showing in another api call. Can you please help me to fix this issue. I have asked this in stackoverflow. Please check the below link
https://stackoverflow.com/questions/72003285/passport-req-session-passport-always-gives-undefined-on-other-api-calls
